### ISSUE TITLE
CORS - any origin

### ISSUE THREAD

**Issue by marcuspflanz** [xapix-io/beta#5]
When performing a request from a webserver one gets a error message in OPTIONS preflight stating:

No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

This could be fixed by providing 'Access-Control-Allow-Origin': * in the headers.

**Comment by oliver-xapix-io** [comment]
Hi Marcus, thx for reporting. Appeared on Angular.

Following your suggestions I set:

```ruby
headers['Access-Control-Allow-Methods'] = 'GET' # 'POST, PUT, DELETE, GET, OPTIONS'    headers['Access-Control-Request-Method'] = '*'
headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
headers['Access-Control-Allow-Origin'] = '*'
```

The headers appear on my Postman and WebCLI on production.

Does anyone else have that Problem?

Can you please keep me updated on this?

Cheers, Oliver

**Comment by oliver-xapix-io** [comment]
UPDATE:

```ruby
headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
```

**Comment by marcuspflanz** [comment]
As promised my colleague David Steinkopff had a look into the issue and brought into his eagle eye: Looks like the server does respond to all OPTIONS calls with a 404.
You may easily reproduce this e.g. via postman by sending an OPTIONS request to any xapix-api resource.

Best regards,
Marcus

**Comment by oliver-xapix-io** [comment]
Thx Marcus! I just took a deeper look into the topic.

It looks like Rails does indeed respond to OPTIONS with 404 by default. I was able to reproduce the issue in Postman, too.

Furthermore I am not 100% sure how Rails by default handles CORS requests, so I installed a Middleware: https://github.com/cyu/rack-cors

On OPTIONS, best resource to be found for me was: http://zacstewart.com/2012/04/14/http-options-method.html

Even though I like the OPTIONS concept I went with the bare minimum for now. I implemented a catch-all route behind http://app.xapix.io/api/v1/* that will respond to everything by returning 200 OK and your HTTP method options.

For what I got the OPTIONS method doesn't have too much traction, but if devs demand more expressive and resource specific responses I am ready to talk. :)

If you could rerun your Angular app against the current setup, this would mean a lot to me, since I want to comfort Angular people as good as possible, too! :) I would super appreciate if you could report if my recent update changed sth for you.

Thx in advance, Oliver

**Comment by marcuspflanz** [comment]
Hi Oliver,

works like a charm now :)
By the way we used Angular but not for everything - thus we used https://github.com/cujojs/rest for web requests instead of Angular' resources (but shouldn't make any difference in this case at all).

Thanks for fixing and best regards,
Marcus
